
package com.practice.emp.employeedirectory.model;

import static com.practice.emp.employeedirectory.model.EmployeePojo.ALL_EMPLOYEES_QUERY_NAME;

import java.io.Serializable;
import java.security.Timestamp;
import java.time.LocalDateTime;

import javax.annotation.ManagedBean;
import javax.faces.view.ViewScoped;
import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;

/**
 *
 * Description: model for the employee object
 */
@Entity(name = "EMPLOYEE")
@Table(name = "EMPLOYEE")
@Access(AccessType.PROPERTY)
@EntityListeners({ EmployeePojoListener.class })
@NamedQueries(@NamedQuery(name = ALL_EMPLOYEES_QUERY_NAME, query = "SELECT e FROM EMPLOYEE e"))

@ManagedBean
@ViewScoped
public class EmployeePojo implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String ALL_EMPLOYEES_QUERY_NAME = "allEmployees";

    protected int id;
    protected String firstName;
    protected String lastName;
    protected String email;
    protected String title;
    protected Double salary;
    protected int version;
    protected LocalDateTime createdDate;
    protected LocalDateTime updateDdate;

    protected transient boolean editable;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return id;
    }

    /**
     * @param id new value for id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the value for firstName
     */
    @Column(name = "fname")
    public String getFirstName() {
        return firstName;
    }

    /**
     * @param firstName new value for firstName
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return the value for lastName
     */
    @Column(name = "lname")
    public String getLastName() {
        return lastName;
    }

    /**
     * @param lastName new value for lastName
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return the value for email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email new value for email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the value for title
     */
    public String getTitle() {
        return title;
    }

    /**
     * @param title new value for title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * @return the value for salary
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * @param salary new value for salary
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    @Column(name = "CREATED_DATE", updatable = false, nullable = false)
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    @PrePersist
    public void setCreatedDate(LocalDateTime now) {
        this.createdDate = now;
        System.out.println("created time " + now);
    }

    @Column(name = "UPDATED_DATE", nullable = false)
    public LocalDateTime getUpdatedDate() {
        return updateDdate;
    }

    @PreUpdate
    public void setUpdatedDate(LocalDateTime now) {
        this.updateDdate = now;
    }

    @Version
    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Transient
    public boolean getEditable() {
        return editable;
    }

    public void setEditable(boolean editable) {
        // TODO Auto-generated method stub
        this.editable = editable;
    }

    // generated by Eclipse

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + id;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof EmployeePojo)) {
            return false;
        }
        EmployeePojo other = (EmployeePojo) obj;
        if (id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Employee [id=").append(id).append(", ");
        if (firstName != null) {
            builder.append("firstName=").append(firstName).append(", ");
        }
        if (lastName != null) {
            builder.append("lastName=").append(lastName).append(", ");
        }
        if (email != null) {
            builder.append("email=").append(email).append(", ");
        }
        if (salary != null) {
            builder.append("salary=").append(salary).append(", ");
        }
        if (title != null) {
            builder.append("title=").append(title);
        }
        builder.append("]");
        return builder.toString();
    }

}